image: node:10

cache:
  paths:
  - node_modules/

# We have two stages to force the jobs to run sequentially
stages:
  - utterance-tests
  - project-tests

utterance-tests:
  stage: utterance-tests
  script:
   - npm install
   - npm run process custom/input/what3words.json
  artifacts:
    paths:
      - results.csv
    expire_in: 30 days
  only: 
    - schedules
    - web

project-tests:
  stage: project-tests
  script:
   - npm install
   - npm test
   - npm run docs
  artifacts:
    paths:
      - test-report.xml
      - docs/
    reports:
      junit: test-report.xml
    expire_in: 30 days
  only:
    - pushes
    - merge_requests