image: node:10.16.3

cache:
  paths:
  - node_modules/

# We have two stages to force the jobs to run sequentially
stages:
  - tests
  - docs
  - server-build
  - server-deploy

tests:10.16.3:
  stage: tests
  script:
    - npm install
    - npm test
    - npm run codecov
  artifacts:
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml
    expire_in: 30 days
  only:
    - pushes
    - merge_requests
  except:
    - /server.*/

tests:12.14.1:
  image: node:12.14.1
  stage: tests
  script:
    - npm install
    - npm test
  only:
    - pushes
    - merge_requests
  except:
    - /server.*/

pages:
  stage: docs
  script:
    - npm install
    - npm run docs
  artifacts:
    paths:
    - public
  only:
    - pushes
    - merge_requests
    - master
  except:
    - /server.*/

server-build:
  stage: server-build
  image: docker:19.03
  services:
    - docker:dind
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker build -f server/Dockerfile -t bespoken/batch-tester:${CI_COMMIT_TAG} .
    - docker push bespoken/batch-tester:${CI_COMMIT_TAG}
  only:
    - /server.*/

server-deploy:
  stage: server-deploy
  script: 
    - npm install fargate-helper -g
    - | 
      fargate service \
      --command "node server/server.js" \
      --name batch-tester \
      --containerPort 3000 \
      --image bespoken/batch-tester:${CI_COMMIT_TAG} \
      --hostname batch-tester.bespoken.io \
      --cpu 256 \
      --memory 512 \
      --env AWS_ACCESS_KEY_ID="${BATCH_AWS_ACCESS_KEY_ID}" \
      --env AWS_SECRET_ACCESS_KEY="${BATCH_AWS_SECRET_ACCESS_KEY}"
  only:
    - /server.*/