image: node:10

cache:
  paths:
  - node_modules/

# We have two stages to force the jobs to run sequentially
stages:
  - tests
  - docs

tests:
  stage: tests
  script:
    - npm install
    - npm test
  artifacts:
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml
    expire_in: 30 days
  only:
    - pushes
    - merge_requests

pages:
  stage: docs
  script:
    - npm install
    - npm run docs
  artifacts:
    paths:
    - public
  only:
    - pushes
    - merge_requests
    - master