image: node:10

cache:
  paths:
  - node_modules/

# We have two stages to force the jobs to run sequentially
stages:
  - show-tests
  - launch-tests

show-tests:
  stage: show-tests
  script:
   - npm install
   - npm run show-tests
  artifacts:
    paths:
    - results.csv
    expire_in: 1 week

launch-tests:
  stage: launch-tests
  script:
   - npm install
   - npm run launch-tests
  artifacts:
    paths:
    - results.csv
    expire_in: 1 week