image: node:10

cache:
  paths:
  - node_modules/

# We have two stages to force the jobs to run sequentially
stages:
  - utterance-tests
  - project-tests

utterance-tests:
  stage: utterance-tests
  script:
   - npm install
   - npm run process custom/input/what3words.json
  artifacts:
    paths:
      - results.csv
    expire_in: 30 days
  only: 
    - schedules
    - web

project-tests:
  stage: project-tests
  script:
   - npm install
   - npm test
  artifacts:
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml
    expire_in: 30 days
  # Got this from here: https://stackoverflow.com/questions/50798747/code-coverage-from-jest-to-stdout-to-gitlab
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  only:
    - pushes
    - merge_requests

pages:
  stage: project-tests
  script:
  - npm run docs
  artifacts:
    paths:
    - public
  only:
    - pushes
    - merge_requests
    - master